import Head from 'next/head';
import { NavBar } from '@/components/NavBar';
import { Project } from '@/components/Project';

export default function Projects() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Project NavBar={<NavBar/>}/>
      </main>
    </>
  );
}
